<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UthandoDomPdf\Module'                             => __DIR__ . '/Module.php',
    'UthandoDomPdf\Form\DomPdfOptionsFieldSet'         => __DIR__ . '/src/UthandoDomPdf/Form/DomPdfOptionsFieldSet.php',
    'UthandoDomPdf\Form\PdfOptionsFieldSet'            => __DIR__ . '/src/UthandoDomPdf/Form/PdfOptionsFieldSet.php',
    'UthandoDomPdf\Form\DomPdfSettings'                => __DIR__ . '/src/UthandoDomPdf/Form/DomPdfSettings.php',
    'UthandoDomPdf\Model\PdfFooterCollection'          => __DIR__ . '/src/UthandoDomPdf/Model/PdfFooterCollection.php',
    'UthandoDomPdf\Model\PdfHeaderCollection'          => __DIR__ . '/src/UthandoDomPdf/Model/PdfHeaderCollection.php',
    'UthandoDomPdf\Model\PdfTextLine'                  => __DIR__ . '/src/UthandoDomPdf/Model/PdfTextLine.php',
    'UthandoDomPdf\Model\PdfTextLineFont'              => __DIR__ . '/src/UthandoDomPdf/Model/PdfTextLineFont.php',
    'UthandoDomPdf\Mvc\Controller\Settings'            => __DIR__ . '/src/UthandoDomPdf/Mvc/Controller/Settings.php',
    'UthandoDomPdf\Mvc\Service\ViewPdfRendererFactory' => __DIR__ . '/src/UthandoDomPdf/Mvc/Service/ViewPdfRendererFactory.php',
    'UthandoDomPdf\Mvc\Service\ViewPdfStrategyFactory' => __DIR__ . '/src/UthandoDomPdf/Mvc/Service/ViewPdfStrategyFactory.php',
    'UthandoDomPdf\Options\DomPdfOptions'              => __DIR__ . '/src/UthandoDomPdf/Options/DomPdfOptions.php',
    'UthandoDomPdf\Options\PdfOptions'                 => __DIR__ . '/src/UthandoDomPdf/Options/PdfOptions.php',
    'UthandoDomPdf\Service\DomPdfFactory'              => __DIR__ . '/src/UthandoDomPdf/Service/DomPdfFactory.php',
    'UthandoDomPdf\Service\DomPdfOptionsFactory'       => __DIR__ . '/src/UthandoDomPdf/Service/DomPdfOptionsFactory.php',
    'UthandoDomPdf\Service\PdfModelFactory'            => __DIR__ . '/src/UthandoDomPdf/Service/PdfModelFactory.php',
    'UthandoDomPdf\View\Model\PdfModel'                => __DIR__ . '/src/UthandoDomPdf/View/Model/PdfModel.php',
    'UthandoDomPdf\View\Renderer\PdfRenderer'          => __DIR__ . '/src/UthandoDomPdf/View/Renderer/PdfRenderer.php',
    'UthandoDomPdf\View\Strategy\PdfStrategy'          => __DIR__ . '/src/UthandoDomPdf/View/Strategy/PdfStrategy.php',
);
